# Generated by Django 5.1 on 2024-09-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "backendApp",
            "0002_patient_line_notify_alter_qrcodepoint_qr_code_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="line_notify",
        ),
        migrations.DeleteModel(
            name="Bed",
        ),
    ]
