# Generated by Django 5.1 on 2024-09-21 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendApp", "0003_remove_supplier_line_notify_delete_bed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turnpoint",
            name="qr_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backendApp.qrcodepoint",
            ),
        ),
    ]
