# Generated by Django 5.1 on 2024-09-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendApp", "0005_actiontype_action_type_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="turnpoint",
            name="turn_point_name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
