# Generated by Django 5.1 on 2024-09-22 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendApp", "0006_turnpoint_turn_point_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routecondition",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backendApp.patient",
            ),
        ),
    ]
