# Generated by Django 5.1 on 2024-09-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backendApp", "0007_alter_routecondition_patient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routecondition",
            old_name="patient",
            new_name="patients",
        ),
    ]
