# Generated by Django 5.0.6 on 2024-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0010_rename_rfidcard_code_rfidcard_rfidcard_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sides',
            name='sides_unit',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
    ]
