# Generated by Django 4.2.6 on 2024-09-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0010_vehicle_vehicle_mac_address_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestatus',
            name='vehicle_state_html_style',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
