# Generated by Django 4.2.6 on 2024-09-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0011_vehiclestatus_vehicle_state_html_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_mac_address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
